services:
  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      args:
        - NGINX_PUBLICDIR=${PUBLICDIR}
        - NGINX_DOMAINNAME=${DOMAINNAME}
    volumes:
      - public_dir:${PUBLICDIR}
    links:
      - wordpress
    ports:
      - 443:443

  mariadb:
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ADMINPWD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_USERPWD}
    build:
      context: ./requirements/mariadb

  wordpress:
    environment:
      - WP_DOMAINNAME=${DOMAINNAME}
      - WP_PUBLICDIR=${PUBLICDIR}
      
      - WP_DBNAME=${DB_NAME}
      - WP_DBUSER=${DB_USERNAME}
      - WP_DBPASSWORD=${DB_USERPWD}
      
      - WP_ADMINNAME=${WP_ADMINNAME}
      - WP_ADMINPWD=${WP_ADMINPWD}
      - WP_ADMINEMAIL=${WP_ADMINEMAIL}
      
      - WP_TITLE=${WP_TITLE}
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      args:
        - WP_PUBLICDIR=${PUBLICDIR}
    volumes:
      - public_dir:${PUBLICDIR}
    links:
      - mariadb:mysql

volumes:
  public_dir: