version: '3.0'
services:
  nginx:
    depends_on:
      - wordpress
    volumes:
      - public_dir:${PUBLICDIR}
    links:
      - wordpress
    ports:
      - 443:443
    restart: on-failure
    build:
      context: ./requirements/nginx
      args:
        - NGINX_PUBLICDIR=${PUBLICDIR}
        - NGINX_DOMAINNAME=${DOMAINNAME}

  mariadb:
    volumes:
      - db_dir:/var/lib/mysql
    restart: on-failure
    build:
      context: ./requirements/mariadb
      args:
        - MARIADB_DATABASE=${DB_NAME}
        - MARIADB_USER=${DB_USERNAME}
        - MARIADB_PASSWORD=${DB_USERPWD}

  wordpress:
    volumes:
      - public_dir:${PUBLICDIR}
    links:
      - mariadb:mysql
    depends_on:
      - mariadb
    environment:
      - WP_DOMAINNAME=${DOMAINNAME}
      - WP_PUBLICDIR=${PUBLICDIR} 
      - WP_ADMINNAME=${WP_ADMINNAME}
      - WP_ADMINPWD=${WP_ADMINPWD}
      - WP_ADMINEMAIL=${WP_ADMINEMAIL}
      
      - WP_TITLE=${WP_TITLE}
    build:
      context: ./requirements/wordpress
      args:
        - WP_PUBLICDIR=${PUBLICDIR}
        - WP_DBNAME=${DB_NAME}
        - WP_DBUSER=${DB_USERNAME}
        - WP_DBPASSWORD=${DB_USERPWD}

volumes:
  public_dir:
  db_dir: