version: '3.0'
services:
  nginx:
    depends_on:
      - wordpress
    volumes:
      -  public_vol:${PUBLICDIR}
    networks:
      front:
    ports:
      - 443:443
    restart: always
    build:
      context: ./requirements/nginx
      args:
        - NGINX_PUBLICDIR=${PUBLICDIR}
        - NGINX_DOMAINNAME=${DOMAINNAME}

  mariadb:
    volumes:
      - db_vol:/var/lib/mysql
    restart: always
    build:
      context: ./requirements/mariadb
      args:
        - MARIADB_DATABASE=${DB_NAME}
        - MARIADB_USER=${DB_USERNAME}
        - MARIADB_PASSWORD=${DB_USERPWD}
    networks:
      back:
        aliases:
          - mysql

  wordpress:
    volumes:
      - public_vol:${PUBLICDIR}
    restart: always
    networks:
      front:
      back:
    depends_on:
      - mariadb
    environment:
      - WP_DOMAINNAME=${DOMAINNAME}
      - WP_ADMINNAME=${WP_ADMINNAME}
      - WP_ADMINPWD=${WP_ADMINPWD}
      - WP_ADMINMAIL=${WP_ADMINMAIL}
      - WP_TITLE=${WP_TITLE}
      - WP_USERNAME=${WP_USERNAME}
      - WP_USERPWD=${WP_USERPWD}
      - WP_USERMAIL=${WP_USERMAIL}
    build:
      context: ./requirements/wordpress
      args:
        - WP_PUBLICDIR=${PUBLICDIR}
        - WP_DBNAME=${DB_NAME}
        - WP_DBUSER=${DB_USERNAME}
        - WP_DBPASSWORD=${DB_USERPWD}

networks:
  front:
  back:

volumes:
  public_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_DIR_WP}
  db_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_DIR_DB}