services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    volumes:
      - wordpress_folder:${PUBLIC_FOLDER}
    ports:
      - 443:443
    links:
      - wordpress
  mariadb:
    build: ./requirements/mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      args:
        - WP_FOLDER=${PUBLIC_FOLDER}
    stdin_open: true 
    tty: true
    environment:
      - WP_DBNAME=${DB_NAME}
      - WP_DBUSER=${DB_USER}
      - WP_DBPASSWORD=${DB_PASSWORD}
      - WP_FOLDER=${PUBLIC_FOLDER}
    volumes:
      - wordpress_folder:${PUBLIC_FOLDER}
    links:
      - mariadb:mysql

volumes:
  wordpress_folder: